name: Release Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm Deps
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency update chart

      - name: Run chart-releaser
        # uses: patuf/chart-releaser-action@main
        uses: /chart-releaser-action@v1.2.1
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"